on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  cache: 0

jobs:
  focal-llvm_9-bcc_v0_15_0:
    name: focal / llvm 9 / bcc 0.15.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.15.0"
      DIST: focal
      FEATURES: bpf_v0_15_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_16_0:
    name: focal / llvm 9 / bcc 0.16.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.16.0"
      DIST: focal
      FEATURES: bpf_v0_16_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_17_0:
    name: focal / llvm 9 / bcc 0.17.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.17.0"
      DIST: focal
      FEATURES: bpf_v0_17_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_18_0:
    name: focal / llvm 9 / bcc 0.18.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.18.0"
      DIST: focal
      FEATURES: bpf_v0_18_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_19_0:
    name: focal / llvm 9 / bcc 0.19.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.19.0"
      DIST: focal
      FEATURES: bpf_v0_19_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_20_0:
    name: focal / llvm 9 / bcc 0.20.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.20.0"
      DIST: focal
      FEATURES: bpf_v0_20_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_14_0:
    name: focal / llvm 9 / bcc 0.21.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.21.0"
      DIST: focal
      FEATURES: bpf_v0_21_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_22_0:
    name: focal / llvm 9 / bcc 0.22.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.22.0"
      DIST: focal
      FEATURES: bpf_v0_22_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_16_0:
    name: focal / llvm 9 / bcc 0.23.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.23.0"
      DIST: focal
      FEATURES: bpf_v0_23_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_16_0-static:
    name: focal / llvm 9 / bcc 0.23.0 / static
    runs-on: ubuntu-20.04
    env:
      BCC: "0.23.0"
      DIST: focal
      FEATURES: bpf_v0_23_0 bpf_static
      LLVM: 9
      STATIC: true
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  memcache-smoketest:
    name: memcache smoketest
    runs-on: ubuntu-20.04
    env:
      BCC: "0.23.0"
      DIST: focal
      FEATURES: bpf_v0_23_0
      LLVM: 9
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash build/ci.sh
      - name: Smoketest
        run: target/release/rezolus --config configs/memcache.toml & sleep 180; curl -s http://localhost:4242/vars
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Smoketest
        run: target/release/rezolus --config configs/macos.toml & sleep 180; curl -s http://localhost:4242/vars
  musl:
    name: musl
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install rust musl toolchain
        run: rustup target add x86_64-unknown-linux-musl
      - name: update apt
        run: sudo apt-get update
      - name: install musl-tools
        run: sudo apt-get install -y musl-tools
      - name: build
        run: cargo build --release --target x86_64-unknown-linux-musl
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: rustfmt
      run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy || cargo clippy
  # audit:
  #   name: audit
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: install
  #     run: cargo install cargo-audit
  #   - name: audit
  #     run: cargo audit --ignore RUSTSEC-2020-0031